### ISSUE TITLE
Function gives errors when there are untagged images on the ecr repo

### ISSUE THREAD

**Issue by martijnvdp** [CCV-Group/lambda-ecr-image-sync#31]
function returns errors when scanning a ecr repo that contains untagged images

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xb486d5]

goroutine 6 [running]:
testing.tRunner.func1.2(0xb96a60, 0xf3e4e0)
	C:/Program Files/Go/src/testing/testing.go:1144 +0x585
testing.tRunner.func1(0xc000053380)
	C:/Program Files/Go/src/testing/testing.go:1147 +0x3de
panic(0xb96a60, 0xf3e4e0)
	C:/Program Files/Go/src/runtime/panic.go:971 +0x4e6
github.com/CCV-Group/lambda-ecr-image-sync/pkg/handlers.EcrScan(0xc00006f2c0, 0x1, 0x4, 0xc0000961b0, 0x1, 0x1, 0x0, 0x0)
	C:/Users/marti/Documents/code/lambda-ecr-image-sync/pkg/handlers/ecrscan.go:62 +0xd15
github.com/CCV-Group/lambda-ecr-image-sync/pkg/handlers.TestCsv_with_results(0xc000053380)
	lambda-ecr-image-sync/pkg/handlers/csv_test.go:33 +0x399
testing.tRunner(0xc000053380, 0xc2f068)
	C:/Program Files/Go/src/testing/testing.go:1194 +0x1a3
created by testing.(*T).Run
	C:/Program Files/Go/src/testing/testing.go:1239 +0x63c

**Comment by martijnvdp** [comment]
https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_ListImages.html

filter options tagged only
